name: example
description: "A Flutter example app for the dart_pdf_translator package."
publish_to: 'none' # Remove this line if you want to publish this example separately

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- Project Dependencies ---

  # Add a path dependency to the parent package
  dart_pdf_translator:
    path: ../

  # For picking PDF files
  file_picker: ^8.0.0+1
  
  # For rendering the translated Markdown output
  flutter_markdown: ^0.7.1

  # For extracting text from PDF files in a Flutter environment
  syncfusion_flutter_pdf: ^26.1.35
  
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true